services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    depends_on:
      - web
    restart: unless-stopped

networks:
  default:
    name: aizeva_network